conventions_server/src/Entity/Plan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlanRepository")
 */
class Plan implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Konwent", inversedBy="plans")
     * @ORM\JoinColumn(nullable=false)
     */
    private $konwent;

    /**
     * @ORM\Column(type="time")
     */
    private $czas_rozpoczecia;

    /**
     * @ORM\Column(type="time")
     */
    private $czas_zakonczenia;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Zespol", mappedBy="plan", cascade={"persist", "remove"})
     */
    private $zespol;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKonwent(): ?Konwent
    {
        return $this->konwent;
    }

    public function setKonwent(?Konwent $konwent): self
    {
        $this->konwent = $konwent;

        return $this;
    }

    public function getCzasRozpoczecia(): ?\DateTimeInterface
    {
        return $this->czas_rozpoczecia;
    }

    public function setCzasRozpoczecia(\DateTimeInterface $czas_rozpoczecia): self
    {
        $this->czas_rozpoczecia = $czas_rozpoczecia;

        return $this;
    }

    public function getCzasZakonczenia(): ?\DateTimeInterface
    {
        return $this->czas_zakonczenia;
    }

    public function setCzasZakonczenia(\DateTimeInterface $czas_zakonczenia): self
    {
        $this->czas_zakonczenia = $czas_zakonczenia;

        return $this;
    }

    public function getZespol(): ?Zespol
    {
        return $this->zespol;
    }

    public function setZespol(Zespol $zespol): self
    {
        $this->zespol = $zespol;

        // set the owning side of the relation if necessary
        if ($this !== $zespol->getPlan()) {
            $zespol->setPlan($this);
        }

        return $this;
    }

    public function jsonSerialize() : array
    {
        return [
            'id'        =>$this->id,
            'zespol'           => $this->zespol,
            'czas_rozpoczecia'        => $this->czas_rozpoczecia,
            'czas_zakonczenia'         => $this->czas_zakonczenia,
        ];
    }


}

conventions_server/src/Form/PlanType.php
<?php

namespace App\Form;

use App\Entity\Konwent;
use App\Entity\Plan;
use App\Entity\Zespol;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('czas_rozpoczecia')
            ->add('czas_zakonczenia')
            ->add('konwent', EntityType::class, [
                'class' => Konwent::class,
                'choice_label' => 'nazwa'
            ])
            ->add('zespol', EntityType::class, [
                'class' => Zespol::class,
                'choice_label' => 'nazwa'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Plan::class,
        ]);
    }
}

conventions_server/src/Controller/PlanController.php
<?php
/**
 * Created by PhpStorm.
 * User: Michau
 * Date: 2019-01-23
 * Time: 23:35
 */

namespace App\Controller;

use App\Entity\Bilet;
use App\Entity\CzlonekZespolu;
use App\Entity\Gra;
use App\Entity\Konkurs;
use App\Entity\Konwent;
use App\Entity\Plan;
use App\Entity\Produkt;
use App\Entity\Stoisko;
use App\Entity\Uczestnik;
use App\Entity\Zespol;
use FOS\RestBundle\Controller\AbstractFOSRestController;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


class PlanController extends AbstractFOSRestController
{
    /**
     * @Rest\Get("/plans/{id}")
     * @return View
     */
    public function getPlanAction($id): View
    {
        $repository = $this->getDoctrine()->getRepository(Plan::class);
        $plans = $repository->findBy(
            ['konwent' => $id]
        );
        return View::create($plans, Response::HTTP_OK);
    }
}

conventions_server/templates/plan/_delete_form.html.twig
<form method="post" action="{{ path('plan_delete', {'id': plan.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ plan.id) }}">
    <button class="btn">Delete</button>
</form>

conventions_server/templates/plan/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

conventions_server/templates/plan/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Plan{% endblock %}

{% block body %}
    <h1>Edit Plan</h1>

    {{ include('plan/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('plan_index') }}">back to list</a>

    {{ include('plan/_delete_form.html.twig') }}
{% endblock %}

conventions_server/templates/plan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plan index{% endblock %}

{% block body %}
    <h1>Plan index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Czas_rozpoczecia</th>
                <th>Czas_zakonczenia</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for plan in plans %}
            <tr>
                <td>{{ plan.id }}</td>
                <td>{{ plan.czasRozpoczecia ? plan.czasRozpoczecia|date('H:i:s') : '' }}</td>
                <td>{{ plan.czasZakonczenia ? plan.czasZakonczenia|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('plan_show', {'id': plan.id}) }}">show</a>
                    <a href="{{ path('plan_edit', {'id': plan.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

conventions_server/templates/plan/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Plan{% endblock %}

{% block body %}
    <h1>Create new Plan</h1>

    {{ include('plan/_form.html.twig') }}

    <a href="{{ path('plan_index') }}">back to list</a>
{% endblock %}

conventions_server/templates/plan/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plan{% endblock %}

{% block body %}
    <h1>Plan</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ plan.id }}</td>
            </tr>
            <tr>
                <th>Czas_rozpoczecia</th>
                <td>{{ plan.czasRozpoczecia ? plan.czasRozpoczecia|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Czas_zakonczenia</th>
                <td>{{ plan.czasZakonczenia ? plan.czasZakonczenia|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('plan_index') }}">back to list</a>

    <a href="{{ path('plan_edit', {'id': plan.id}) }}">edit</a>

    {{ include('plan/_delete_form.html.twig') }}
{% endblock %}